#! /bin/bash
#
prog=`basename $0`
execdir=`dirname $0`
[ "$execdir" = "" -o "$execdir" = "." ] && execdir=$PWD
export CODEDIR=`(cd $execdir/.. > /dev/null 2>&1; pwd)`
export DOCKERDIR=$execdir

dodockbuild=
(docker images | grep -qs oar-sdp/build) || {
    echo "${prog}: Docker image oar-sdp/build not found; will build."
    dodockbuild=-d
}

echo $DOCKERDIR/run.sh $dodockbuild build "$@"
exec $DOCKERDIR/run.sh $dodockbuild build "$@"
