name: source-update
on:
  workflow_dispatch:
  push:
    branches-ignore: ['main', 'integration']
    paths:
      - 'angular/src/**'
      - 'angular/pom.xml'
jobs:
  buildtest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node.js 14.19
        uses: actions/setup-node@v2
        with:
          node-version: 14.19.0

      - name: Setup dependency caching
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('angular/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node

      - name: Install dependencies
        run: cd angular && npm install

      - name: Run unit tests
        run: cd angular && npm test


  
